version: '2'

volumes:
 mongodb_data:

services:
  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    volumes:
      - mongodb_data:/data/db
    network_mode: host

  webui:
    image: registry.nearbycomputing.com/nbycomp/open5gs  
    depends_on:
      - mongodb
    environment:
      - DB_URI=mongodb://127.0.0.1/open5gs
    container_name: webui
    network_mode: host
    ports:
      - "3000:3000"
    volumes:
        - "./config-standalone:/usr/local/etc:z"
    entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_webui.sh"

  mongodbloader:
    image: mongo:latest
    depends_on:
      - webui
    environment:
      - DB_HOST=127.0.0.1
    network_mode: host
    volumes:
      - "./provisioning/db/run_db.sh:/tmp/run.sh:z"
      - "./provisioning/db/imsi1.json:/tmp/imsi1.json:z"
    entrypoint:
      - /bin/sh
      - /tmp/run.sh

  hss:
    image: registry.nearbycomputing.com/nbycomp/open5gs  
    depends_on:
      - mongodb
    container_name: hss
    network_mode: host
    entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_hss.sh"
    volumes:
      - "./config-standalone:/usr/local/etc:z"
      
  mme:
     image: registry.nearbycomputing.com/nbycomp/open5gs  
     depends_on:
       - hss
     container_name: mme
     network_mode: host
     entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_mme.sh"
     volumes:
      - "./config-standalone:/usr/local/etc:z"

  sgw:
     image: registry.nearbycomputing.com/nbycomp/open5gs  
     container_name: sgw
     network_mode: host
     entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_sgw.sh"
     volumes:
      - "./config-standalone:/usr/local/etc:z"

  pgw:
     image: registry.nearbycomputing.com/nbycomp/open5gs  
     container_name: pgw
     network_mode: host
     entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_pgw.sh"
     volumes:
      - "./config-standalone:/usr/local/etc:z"
     devices:
      - /dev/net/tun
     privileged: true
     cap_add:
       -  NET_ADMIN
      
  pcrf:
    image: registry.nearbycomputing.com/nbycomp/open5gs  
    depends_on:
       - mongodb
       - hss
    container_name: pcrf
    network_mode: host
    entrypoint:
      - "/bin/sh"
      - "/usr/local/etc/run_pcrf.sh"
    volumes:
      - "./config-standalone:/usr/local/etc:z"
